---
- name: Install nginx on Amazon Linux
  become: yes
  shell: |
    amazon-linux-extras enable nginx1
    yum clean metadata
    yum install -y nginx
  args:
    creates: /usr/sbin/nginx

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Remove default nginx site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx

- name: Configure nginx load balancer
  template:
    src: nginx_frontend.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
